gpu_id: 2
multi_gpus: False
num_workers: 4
seed: 666
exp_name: 'expTGIF-QAAction'

train:
  lr: 0.0001
  batch_size: 1
  restore: False
  max_epochs: 25
  word_dim: 300
  module_dim: 512
  glove: True
  k_max_frame_level: 16
  k_max_clip_level: 8
  spl_resolution: 1

val:
  flag: True

test:
  test_num: 0
  write_preds: True

dataset:
  name: 'tgif-qa-infer'
  question_type: 'action'
  data_dir: '/home/kylee/work/projects/5_vqa/hcrn-videoqa/data/tgif-qa-infer/action'
  save_dir: '/home/kylee/work/projects/5_vqa/hcrn-videoqa/results/'